# bacon.toml — hot-reload para Axum
default_job = "run-long"
env.CARGO_TERM_COLOR = "always"

[jobs.run-long]
command = ["cargo", "run", "--color", "always"]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"
watch = [
  "src/**",         # ← recursivo
  "Cargo.toml",
  ".env",
  "data/users.json",
  "data/**"         # ← recursivo
]

[keybindings]
r = "job:run-long"
